import axios from 'axios';
import dotenv from 'dotenv';

dotenv.config();

const TTLOCK_CLIENT_ID = process.env.TTLOCK_CLIENT_ID;
const TTLOCK_CLIENT_SECRET = process.env.TTLOCK_CLIENT_SECRET;
const TTLOCK_API_BASE_URL = process.env.TTLOCK_API_BASE_URL || 'https://api.sciener.com';

/**
 * Upgrade Check
 * Check to see whether there is any upgrade for a lock
 * If there is no version info on the server, returns 'unknown'
 * Endpoint: POST /v3/lock/upgradeCheck
 *
 * @param {Object} req - Express request object
 * @param {string} req.body.accessToken - Access token
 * @param {number} req.body.lockId - Lock ID
 * @returns {Object} Response with upgrade availability info
 */
export const upgradeCheck = async (req, res) => {
  try {
    const { accessToken, lockId } = req.body;

    // Validate required fields
    if (!accessToken) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_ACCESS_TOKEN',
          message: 'Access token is required'
        }
      });
    }

    if (!lockId) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_LOCK_ID',
          message: 'Lock ID is required'
        }
      });
    }

    console.log('= TTLock Upgrade Check');
    console.log('   Lock ID:', lockId);

    // Prepare request parameters
    const params = {
      clientId: TTLOCK_CLIENT_ID,
      accessToken: accessToken,
      lockId: lockId,
      date: Date.now()
    };

    console.log('=� Calling TTLock Upgrade Check API...');

    // Call TTLock API
    const response = await axios.post(
      `${TTLOCK_API_BASE_URL}/v3/lock/upgradeCheck`,
      null,
      { params }
    );

    console.log('=� Response:', response.data);

    // Check for errors
    if (response.data.errcode && response.data.errcode !== 0) {
      console.error('L TTLock upgrade check error:', response.data);

      // Special handling for common errors
      let errorMessage = response.data.errmsg || response.data.description || 'Failed to check upgrade';
      let errorCode = 'UPGRADE_CHECK_FAILED';

      if (response.data.errcode === -1) {
        errorMessage = 'Invalid access token';
        errorCode = 'INVALID_TOKEN';
      } else if (response.data.errcode === -2003) {
        errorMessage = 'Lock not found';
        errorCode = 'LOCK_NOT_FOUND';
      } else if (response.data.errcode === -2018) {
        errorMessage = 'Permission denied - you do not have access to this lock';
        errorCode = 'PERMISSION_DENIED';
      }

      return res.status(400).json({
        success: false,
        error: {
          code: errorCode,
          message: errorMessage,
          ttlock_errcode: response.data.errcode
        }
      });
    }

    const { needUpgrade, firmwareInfo, firmwarePackage, version } = response.data;

    console.log(' Upgrade check completed');
    console.log('   Need Upgrade:', getUpgradeStatusText(needUpgrade));

    // Return response with enhanced data
    res.json({
      success: true,
      message: 'Upgrade check completed successfully',
      data: {
        lockId: lockId,
        needUpgrade: needUpgrade,
        upgradeStatusText: getUpgradeStatusText(needUpgrade),
        firmwareInfo: firmwareInfo || null,
        firmwarePackage: firmwarePackage || null,
        latestVersion: version || null,
        isUpgradeAvailable: needUpgrade === 1,
        isUpgradeNotNeeded: needUpgrade === 0,
        isVersionUnknown: needUpgrade === 2,
        checkedAt: new Date().toISOString(),
        requiresRecheck: needUpgrade === 2
      }
    });
  } catch (error) {
    console.error('L Upgrade check error:', error.response?.data || error.message);
    res.status(500).json({
      success: false,
      error: {
        code: 'SERVER_ERROR',
        message: error.response?.data?.errmsg || error.response?.data?.description || 'Failed to check upgrade',
        details: error.message
      }
    });
  }
};

/**
 * Helper function to convert upgrade status code to text
 * @param {number} status - Upgrade status code
 * @returns {string} Upgrade status text
 */
function getUpgradeStatusText(status) {
  const statusMap = {
    0: 'No upgrade available',
    1: 'Upgrade available',
    2: 'Unknown - recheck required'
  };
  return statusMap[status] || 'Unknown';
}

/**
 * Upgrade Recheck
 * Recheck to see whether there is any upgrade for a lock with lockData from SDK
 * Warning: Please make sure the lockData is from the SDK method
 * Endpoint: POST /v3/lock/upgradeRecheck
 *
 * @param {Object} req - Express request object
 * @param {string} req.body.accessToken - Access token
 * @param {number} req.body.lockId - Lock ID
 * @param {string} req.body.lockData - Lock data generated by SDK
 * @returns {Object} Response with upgrade availability info
 */
export const upgradeRecheck = async (req, res) => {
  try {
    const { accessToken, lockId, lockData } = req.body;

    // Validate required fields
    if (!accessToken) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_ACCESS_TOKEN',
          message: 'Access token is required'
        }
      });
    }

    if (!lockId) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_LOCK_ID',
          message: 'Lock ID is required'
        }
      });
    }

    if (!lockData) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_LOCK_DATA',
          message: 'Lock data is required (from SDK)'
        }
      });
    }

    console.log('= TTLock Upgrade Recheck');
    console.log('   Lock ID:', lockId);
    console.log('   Lock Data Length:', lockData.length);

    // Prepare request parameters
    const params = {
      clientId: TTLOCK_CLIENT_ID,
      accessToken: accessToken,
      lockId: lockId,
      lockData: lockData,
      date: Date.now()
    };

    console.log('=� Calling TTLock Upgrade Recheck API...');

    // Call TTLock API
    const response = await axios.post(
      `${TTLOCK_API_BASE_URL}/v3/lock/upgradeRecheck`,
      null,
      { params }
    );

    console.log('=� Response:', response.data);

    // Check for errors
    if (response.data.errcode && response.data.errcode !== 0) {
      console.error('L TTLock upgrade recheck error:', response.data);

      // Special handling for common errors
      let errorMessage = response.data.errmsg || response.data.description || 'Failed to recheck upgrade';
      let errorCode = 'UPGRADE_RECHECK_FAILED';

      if (response.data.errcode === -1) {
        errorMessage = 'Invalid access token';
        errorCode = 'INVALID_TOKEN';
      } else if (response.data.errcode === -3) {
        errorMessage = 'Invalid parameter - lock data must be valid data from SDK';
        errorCode = 'INVALID_PARAMETER';
      } else if (response.data.errcode === -2003) {
        errorMessage = 'Lock not found';
        errorCode = 'LOCK_NOT_FOUND';
      } else if (response.data.errcode === -2018) {
        errorMessage = 'Permission denied - you do not have access to this lock';
        errorCode = 'PERMISSION_DENIED';
      } else if (response.data.errcode === -3015) {
        errorMessage = 'Invalid lock data - lock data must be from SDK';
        errorCode = 'INVALID_LOCK_DATA';
      }

      return res.status(400).json({
        success: false,
        error: {
          code: errorCode,
          message: errorMessage,
          ttlock_errcode: response.data.errcode
        }
      });
    }

    const { needUpgrade, firmwareInfo, firmwarePackage, version } = response.data;

    console.log(' Upgrade recheck completed');
    console.log('   Need Upgrade:', getUpgradeStatusText(needUpgrade));

    // Return response with enhanced data
    res.json({
      success: true,
      message: 'Upgrade recheck completed successfully',
      data: {
        lockId: lockId,
        needUpgrade: needUpgrade,
        upgradeStatusText: getUpgradeStatusText(needUpgrade),
        firmwareInfo: firmwareInfo || null,
        firmwarePackage: firmwarePackage || null,
        latestVersion: version || null,
        isUpgradeAvailable: needUpgrade === 1,
        isUpgradeNotNeeded: needUpgrade === 0,
        isVersionUnknown: needUpgrade === 2,
        checkedAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('L Upgrade recheck error:', error.response?.data || error.message);
    res.status(500).json({
      success: false,
      error: {
        code: 'SERVER_ERROR',
        message: error.response?.data?.errmsg || error.response?.data?.description || 'Failed to recheck upgrade',
        details: error.message
      }
    });
  }
};
